### ISSUE TITLE
Crash resilience

### ISSUE THREAD

**Issue by maddie** [roseduan/rosedb#56]
请问，有测试过在各平台上(Linux/Windows)突然断电或者程序突然结束的情况下的表现吗？

现在手上有个项目在用badgerdb，但是在Windows下突然断电或者退出程序会导致数据库损坏无法启动，正在找一个替换的方案。

**Comment by auula** [comment]
你可以在操作时候记录操作日子 然后回滚日志
--------------原始邮件--------------
发件人："maddie ***@***.***&gt;;
发送时间：2021年10月13日(星期三) 晚上6:09
收件人："roseduan/rosedb" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[roseduan/rosedb] Crash resilience (#56)
-----------------------------------

 

 
请问，有测试过在各平台上(Linux/Windows)突然断电或者程序突然结束的情况下的表现吗？
 
现在手上有个项目在用badgerdb，但是在Windows下突然断电或者退出程序会导致数据库损坏无法启动，正在找一个替换的方案。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by roseduan** [comment]
还没有测过。
但是 rosedb 的读写流程很简单（更可控），在保证日志文件存在的情况下，无论系统如何 crash，都能够正常启动。
如果你打算使用 rosedb 的话，我可以提供支持。

**Comment by maddie** [comment]
rosedb刚好可以替换掉badger (HSet/HGet)以及我基于badger改的goque (LPush/RPop)，现在正在本地测试，有问题再开issue

感谢！
